echo1:
	go run ch01_01_echo1.go
dup1:
	go run ch01_02_dup1.go
dup2:
	go run ch01_02_dup2.go f.txt
dup3:
	go run ch01_02_dup3.go f.txt
lissajout1:
	go run ch01_04_lissajous1.go > lissajous.gif
fetch1:
	go run ch01_05_fetch1.go http://example.com/
fetchall1:
	go run ch01_06_fetchall1.go http://example.com/ http://example.com/ http://example.com/
071:
	go run ch07_071.go
ttp01:
	go run ch07_07_http01.go
ttp02:
	go run ch07_07_http02.go
ttp03:
	go run ch07_07_http03.go
ttp04:
	go run ch07_07_http04.go