echo1:
	go run ch01_01_echo1.go
dup1:
	go run ch01_02_dup1.go
dup2:
	go run ch01_02_dup2.go f.txt
dup3:
	go run ch01_02_dup3.go f.txt
lissajout1:
	go run ch01_04_lissajous1.go > lissajous.gif
fetch1:
	go run ch01_05_fetch1.go http://example.com/
fetchall1:
	go run ch01_06_fetchall1.go http://example.com/ http://example.com/ http://example.com/
spiner1:
	go run ch08_01_spiner1.go
clock1:
	go run ch08_02_clock1.go
clock2:
	go run ch08_02_clock2.go
reverb1:
	go run ch08_03_reverb1.go
reverb2:
	go run ch08_03_reverb2.go
netcat2:
	go run ch08_03_netcat2.go
ftp:
	go run ch08_02_ftp1.go
nc:
	nc localhost 8888
071:
	go run ch07_071.go
ttp01:
	go run ch07_07_http01.go
ttp02:
	go run ch07_07_http02.go
ttp03:
	go run ch07_07_http03.go
ttp04:
	go run ch07_07_http04.go