w01:
	go run web_01.go
w02:
	go run web_02.go
w03:
	go run web_03.go
w04:
	go run web_04.go
w05:
	go run web_05.go
w06:
	go run web_06.go
w07:
	go run web_07.go
w08:
	go run web_08.go
http2:
	curl -I --http2 --insecure  https://localhost:8080/ 